import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FolderTree, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Button } from '../../components/Button';
import { ConfirmDialog } from '../../components/ConfirmDialog';
import { EmptyState } from '../../components/EmptyState';
import { LoadingState } from '../../components/LoadingState';
import { Modal } from '../../components/Modal';
import { PageHeader } from '../../components/PageHeader';
import { ADMIN_API, apiRequest, unwrapList } from '../../lib/api';
import { formatDate } from '../../lib/format';
import type { Category } from '../../types/domain';

const schema = z.object({ name: z.string().min(2, 'Name is required.').max(80) });
type Values = z.infer<typeof schema>;

export function CategoriesPage() {
  const queryClient = useQueryClient();
  const [creating, setCreating] = useState(false);
  const [deleting, setDeleting] = useState<Category | null>(null);
  const query = useQuery({ queryKey: ['categories'], queryFn: async () => unwrapList<Category>(await apiRequest(ADMIN_API.categories), ['categories']) });
  const { register, handleSubmit, reset, formState: { errors } } = useForm<Values>({ resolver: zodResolver(schema) });
  const createMutation = useMutation({ mutationFn: (values: Values) => apiRequest(ADMIN_API.categories, { method: 'POST', body: values }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['categories'] }); reset(); setCreating(false); } });
  const deleteMutation = useMutation({ mutationFn: (id: string) => apiRequest(ADMIN_API.category(id), { method: 'DELETE' }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['categories'] }); setDeleting(null); } });
  if (query.isLoading) return <LoadingState label="Loading categories" />;
  const categories = query.data ?? [];
  return <div>
    <PageHeader eyebrow="Catalog structure" title="Categories" description="Organize products into clear storefront collections." actions={<Button onClick={() => setCreating(true)}><Plus size={17} /> New category</Button>} />
    <section className="panel">
      {categories.length ? <div className="category-grid">{categories.map((category) => <article className="category-card" key={category.id}><div className="category-card__icon"><FolderTree size={20} /></div><div><strong>{category.name}</strong><span>{category.slug ?? 'Automatic slug'}</span></div><div className="category-card__meta"><span>{category.productCount ?? 0} products</span><small>{formatDate(category.createdAt)}</small></div><button className="icon-button icon-button--danger" onClick={() => setDeleting(category)} aria-label={`Delete ${category.name}`}><Trash2 size={16} /></button></article>)}</div> : <EmptyState icon={FolderTree} title="No categories yet" description="Create a category to organize the product catalog." actionLabel="Create category" onAction={() => setCreating(true)} />}
    </section>
    <Modal isOpen={creating} onClose={() => setCreating(false)} title="Create category" description="Category slugs can be generated by the backend." size="sm"><form className="form-stack" onSubmit={handleSubmit((values) => createMutation.mutate(values))}><label className="field"><span>Category name</span><input autoFocus placeholder="Home & Living" {...register('name')} />{errors.name ? <small>{errors.name.message}</small> : null}</label>{createMutation.error ? <div className="form-alert">{createMutation.error.message}</div> : null}<div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setCreating(false)}>Cancel</Button><Button type="submit" isLoading={createMutation.isPending}>Create category</Button></div></form></Modal>
    <ConfirmDialog isOpen={Boolean(deleting)} title="Delete this category?" description={`Delete ${deleting?.name ?? 'this category'}. The backend should reject this action when products are still assigned.`} confirmLabel="Delete category" isLoading={deleteMutation.isPending} onClose={() => setDeleting(null)} onConfirm={() => deleting && deleteMutation.mutate(deleting.id)} />
  </div>;
}
